/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/AboutView': RouteRecordInfo<'/AboutView', '/AboutView', Record<never, never>, Record<never, never>>,
    '/BigDataDemo/demo1': RouteRecordInfo<'/BigDataDemo/demo1', '/BigDataDemo/demo1', Record<never, never>, Record<never, never>>,
    '/BigDataDemo/demo1.story': RouteRecordInfo<'/BigDataDemo/demo1.story', '/BigDataDemo/demo1/story', Record<never, never>, Record<never, never>>,
    '/CountDemo': RouteRecordInfo<'/CountDemo', '/CountDemo', Record<never, never>, Record<never, never>>,
    '/FetchDemo': RouteRecordInfo<'/FetchDemo', '/FetchDemo', Record<never, never>, Record<never, never>>,
    '/HomeView': RouteRecordInfo<'/HomeView', '/HomeView', Record<never, never>, Record<never, never>>,
    '/MouseTracker': RouteRecordInfo<'/MouseTracker', '/MouseTracker', Record<never, never>, Record<never, never>>,
    '/TeleportDemo': RouteRecordInfo<'/TeleportDemo', '/TeleportDemo', Record<never, never>, Record<never, never>>,
    '/TestAutoRoute/': RouteRecordInfo<'/TestAutoRoute/', '/TestAutoRoute', Record<never, never>, Record<never, never>>,
  }
}
